version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: postgres_enss
    restart: always
    environment:
      POSTGRES_DB: enss
      POSTGRES_USER: pgadmin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
